### ISSUE TITLE
Npm publish

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes-protocol-decoder#3]
@mcollina Would you mind to publish this to npm? So we can update aedes then

**Comment by mcollina** [comment]
You can publish this yourself. Just add me an another owner.

Il giorno lun 3 feb 2020 alle ore 11:09 Daniel Lando <
notifications@github.com> ha scritto:

**Comment by robertsLando** [comment]
@mcollina What do you use to create new releases here in github? Because I usually use a tool named 
[release-it](https://github.com/release-it/release-it). Anyway I add you as a owner now

**Comment by mcollina** [comment]
manually or via https://www.npmjs.com/package/releasify. Any tool is good anyway.
